### ISSUE TITLE
Firmware for ST-Link clone

### ISSUE THREAD

**Issue by trembel** [amitesh-singh/FASTUSBasp#11]
Hi,

I've two question to your firmware:
- Is it possible to directly flash it onto a ST-Link clone or are there some small changes needed? https://www.hobbiton.be/blog/repurpose-stlink/
- Does it support the TPI programming for the small attiny4/5/9/10?
Best, trembel

**Comment by trembel** [comment]
Seems as if only a small wire is needed from PB15 to PB8, and removing R7, R8, R12.
And some smaller fw changes, e.g. to set RST to PB6 and LED to PA9..

But the question for me is if it supports TPI?

**Comment by amitesh-singh** [comment]
> Seems as if only a small wire is needed from PB15 to PB8, and removing R7, R8, R12.
> And some smaller fw changes, e.g. to set RST to PB6 and LED to PA9..
> 
> But the question for me is if it supports TPI?

no, it does not support TPI
