### ISSUE TITLE
Avrdude for Windows: Can't find programmer id "usbasp-clone"

### ISSUE THREAD

**Issue by nightgryphon** [amitesh-singh/FASTUSBasp#12]
it seems there is no programmer type "usbasp-clone" within windows release of avrdude. Is it possible to solve this?
I've got avrdude here https://sourceforge.net/projects/winavr/

```
C:\WinAVR-20100110\bin>avrdude -c usbasp-clone -p m16

avrdude: Can't find programmer id "usbasp-clone"

Valid programmers are:
  c2n232i  = serial port banging, reset=dtr sck=!rts mosi=!txd miso=!cts [C:\WinAVR-20100110\bin\avrdude.conf:876]
  dasa3    = serial port banging, reset=!dtr sck=rts mosi=txd miso=cts [C:\WinAVR-20100110\bin\avrdude.conf:863]
........
```

**Comment by amitesh-singh** [comment]
which version of avrdude are you using?
I suggest to use latest avrdude version.

avrdude version 6.3, URL: <http://savannah.nongnu.org/projects/avrdude/>

you can find binary version here: https://github.com/takesako/avrdude-win32
