### ISSUE TITLE
Verify FASTUSBasp on Windows OS

### ISSUE THREAD

**Issue by amitesh-singh** [amitesh-singh/FASTUSBasp#4]
I don't own a windows PC at home. It would be nice if someone helps in validating FASTUSBasp on windows OS.

**Comment by posystorage** [comment]
Hello, I try to burn the firmware (in stm32f103rct6, either fastusbasp.bin or fastusbasp-wrongpullup.bin) In the windows PC, the system shows usb get description failed (configuration descriptor is invalid)
This is the usb descriptor file
[fastusbasp  usb description.txt](https://github.com/amitesh-singh/FASTUSBasp/files/1688455/fastusbasp.usb.description.txt)
I think it may be missing the CDC Interface Descriptor and Endpoint Descriptor

I tried define USBDPLUS_WRONG_PULLUP=1
and modified the code here
![2](https://user-images.githubusercontent.com/19422457/35722121-fa2e80da-082f-11e8-8ca5-b67f0835441a.JPG)
However it also did not work

**Comment by posystorage** [comment]
this is the usb enumeration process data which obtained by using the logic analyzer 
[untitled.txt](https://github.com/amitesh-singh/FASTUSBasp/files/1688517/untitled.txt)

**Comment by amitesh-singh** [comment]
Thanks. 
do you have installed usb driver on windows?

Try following driver

http://zadig.akeo.ie/

**Comment by posystorage** [comment]
I have installed the usb driver, and it works fine when using the "fastusbasp v1" firmware.

I get another PC which is  windows7 OS,it works fine，no matter which firmware it is（v1 or v2）
But v2 firmware does not work in  windows10

**Comment by amitesh-singh** [comment]
Thanks for the detailed report.
Firmware V1 & V2 works on Windows 7 OS
Firmware V1 works on Windows 10 but Firmware V2 does not work on windows 10.
The difference between firmware V1 & v2 is the addition of USB-CDC(usb serial) into V2.

Sorry, I don't have any device running windows 7 or 10. This might needs to be checked by some Windows OS expert.

**Comment by posystorage** [comment]
I analyzed the enumeration process and found that after the host requested the configuration descriptor, the device seems like returned the wrong configuration description data.
So when Windows received the wrong configuration descriptor, the system reset the usb bus, re-enumeration,  error again, after three consecutive errors, the enumeration failed.

another a problem, v2 firmware should enumerate two usb devices: serial port (VCP) and FASTUSBasp, but even in the Windows7 OS, it can only enumerate FASTUSBasp, but no serial port.

**Comment by posystorage** [comment]
I think there is something wrong with the content of configuration descriptors
It is not standard, so that some OS do not recognize it, and some OS ignore these problems
for example：
v2 firmware configuration description
	bLength=0x0D
	bDescriptorType=0x02 CONFIGURATION
	wTotalLength=0x0094
	bNumInterfaces=0x03
	bConfigurationValue=0x01
	iConfiguration=0x00
	bmAttributes=0x80 Bus powered, Remote wakeup unsupported
	bMaxPower=0x32 100mA
	byte=0xD8
	byte=0x25
	byte=0x00
	byte=0x08
        bLength=0x08
	bDescriptorType=0x0B <unknown>
	byte=0x00
	byte=0x02
	byte=0x02
	byte=0x02
	byte=0x01
	byte=0x00
...........

USB standard configuration description should be
    /*Configuration Descriptor*/
    0x09,   /* bLength: Configuration Descriptor size */
    USB_CONFIGURATION_DESCRIPTOR_TYPE,      /* bDescriptorType: Configuration  0x02 */
    0x27,       /* wTotalLength:no of returned bytes */
    0x00,
    0x01,   /* bNumInterfaces: 1 interface */
    0x01,   /* bConfigurationValue: Configuration value */
    0x00,   /* iConfiguration: Index of string descriptor describing the configuration */
    0x80,   /* bmAttributes: self powered */
    0x32,   /* MaxPower 32 mA */
    /*Interface Descriptor*/
    0x09,   /* bLength: Interface Descriptor size */
    USB_INTERFACE_DESCRIPTOR_TYPE,  /* bDescriptorType: Interface */
    /* Interface descriptor type */
    0x00,   /* bInterfaceNumber: Number of Interface */
    0x00,   /* bAlternateSetting: Alternate setting */
    0x03,   /* bNumEndpoints: 3 endpoints used */
    0xff,   /* bInterfaceClass: Communication Interface Class */
    0xff,   /* bInterfaceSubClass: Abstract Control Model */
    0xff,   /* bInterfaceProtocol: Common AT commands */
    0x04,   /* iInterface: */
...........


![1](https://user-images.githubusercontent.com/19422457/35744452-5f4bb384-087b-11e8-943c-4b477166f85c.JPG)
![2](https://user-images.githubusercontent.com/19422457/35744460-65494832-087b-11e8-964c-3e15202ce214.JPG)
Universal Serial Bus Specification Revision 2.0 
page 265

I use the STM32F10x standard peripheral library and STM32F10x USB full-speed device library which is official library by STMicroelectronics ，so it is hard for me to understand the libopencm3 .It contains too many files, let me feel faint

So I hope to get your help, thanks.

**Comment by amitesh-singh** [comment]
I got some pointers regarding fixing endpoints in usb cdc descriptor. I shall give it a try this week when i get time.

Thanks a lot to provide detailed debug informations.

**Comment by amitesh-singh** [comment]
i pushed a small fix.

could you please try with this fix?
you do need to rebuild the project.

https://github.com/amitesh-singh/FASTUSBasp/commit/adf6f53b29b1322804abe90e93d6fa5eb1e4fa49
Please let me know if it solves the issue.

**Comment by posystorage** [comment]
I just tried it.It did not work.😫

**Comment by cdtsilva** [comment]
Can someone post a copy of the V1 firmware (no serial) that is supposed to work on Win10?

**Comment by f4grx** [comment]
since this is a composite device, windows probably needs an .inf file to be able to manage both the fastusbasp (what is it ? HID?) AND the CDC ACM Virtual com port.

**Comment by seaspacio** [comment]
can you please provide a V1 compiled firmware?

**Comment by binarymaker** [comment]
![Capture](https://user-images.githubusercontent.com/45413608/67828434-63d1b800-faf9-11e9-818c-6ecf260e7749.PNG)
In windows8 also not work. i tried master and cdc-fix branches.

**Comment by Spider84** [comment]
Hello! I has fixed this issue: https://github.com/amitesh-singh/FASTUSBasp/pull/8

**Comment by amitesh-singh** [comment]
Thanks to this patch, https://github.com/amitesh-singh/FASTUSBasp/commit/8e50587327878244815f05512673f850ab48613e, 
by @Spider84 , FASTUSBasp is supported on Windows.

**Comment by Spider84** [comment]
Glad to help. Thx for firmware. Very helped me to flash single AVR in my STM32 world :)
