### ISSUE TITLE
Reset after programming

### ISSUE THREAD

**Issue by mkSaBtsy** [amitesh-singh/FASTUSBasp#5]
First to say: Great project.
FASTUSBasp is way faster than my AVRISPmkII clone which I couldn't get working under Win7-64 anyway. 

Now my issue:
I'm using AVRDUDESS / Win7-64 to program an ATmega328p. Everything is working well. 
But after any action the reset line stays low, keeping the microcontroller in reset state. What I'm doing wrong?
Please help.

**Comment by amitesh-singh** [comment]
Hello
Thanks for the feedback. It seems like a bug. 
I should set the RST pin to input on disconnect.

**Comment by amitesh-singh** [comment]
Hello again, 

i added the fix and updated the binaries too.
Please let me know if it fixes the issue.

https://github.com/amitesh-singh/FASTUSBasp/commit/8fc50ff744d3d3653f113068feb581d30c6b52c3

Thanks

**Comment by mkSaBtsy** [comment]
Hello
Thanks a lot for the fast update. I flashed new firmware with ST-Link but unfortunately the RST line keeps low again.

**Comment by mkSaBtsy** [comment]
Shouldn't you use 
`rst.setMode(PinMode::INPUT, PinConfig::INPUT_FLOAT);`
instead of 
`rst.setMode(PinMode::OUTPUT_2MHZ, PinConfig::INPUT_FLOAT);`
?
For pins mosi and sck this would apply too.
Can you change this and compile again? I'm new to ARM programming and not able to set up the project in Eclipse (under Windows) properly.

**Comment by amitesh-singh** [comment]
Oops.. good catch .. i will update the code and binary.
Thanks.

**Comment by amitesh-singh** [comment]
i updated the binaries and code. please check it again.

**Comment by mkSaBtsy** [comment]
Dear Amitsh Singh
Now FastUSBasp works like a charm. Thumbs up.

In the mean time (since you uploaded the new binaries not necessary anymore) I tried to build FASTUSBasp on a fresh installed VM Ubuntu Linux. Do you know, if there's a difference between arch linux and ubuntu when disabling standard paths? Libopencm3 compiles without a problem but when linking FASTUSBasp make complains about missing libopencmw_stm32f1.ld file which is in FASTUSBasp directory.

Anyway. Many thanks for this great project.

**Comment by amitesh-singh** [comment]
Or you can create separate md file (say windows.md) for guide.

**Comment by mkSaBtsy** [comment]
Hello 
I tried again to compile with fresh installed Ubuntu 18.04:

- [x] sudo apt-get update
- [x] sudo apt-get upgrade
- [x] sudo apt-get install git cmake make python gcc-arm-none-eabi
- [x] git clone https://github.com/libopencm3/libopencm3)
- [x] cd libopencm3
- [x] make
->compiles without problem

- [x] git clone https://github.com/amitesh-singh/FASTUSBasp
- [x] cd FASTUSBasp
- [x] nano config.cmake 
->set(LIBOPENCM3_DIR "/home/mksabtsy/libopencm3")
- [x] cmake .
cmake . ends up in 4 warnings concerning deprecation (see attached screenshot)
![18-cmake](https://user-images.githubusercontent.com/38809530/39561395-9605342a-4ea5-11e8-910d-bde2dd489945.JPG)

- [x] make

-> as far as I can see, building works, but linking fails because of missing libopencm3_stm32f1.ld file.

![19-make failed](https://user-images.githubusercontent.com/38809530/39561468-21590e02-4ea6-11e8-99ea-675772c14648.JPG)

libopencm3_stm32f1.ld is located in FASTUSBasp directory (.). I guess unlinking system paths does not work properly.

Now I'm short of time, but I could write a short instruction how to use FASTUSBasp with Win7/64. Maybe later even for Win10/64. 
What about the pull request? Should I place my instructions there?

**Comment by amitesh-singh** [comment]
Yes. please provide a pull request regarding the instructions for windows setup.

**Comment by amitesh-singh** [comment]
Hi,

I fixed the compilation issue on Ubuntu. 
Refer to https://github.com/amitesh-singh/FASTUSBasp/commit/e4bc3f48ea11e421ee3d1f94b6a9a09a7d714ec1
