### ISSUE TITLE
Make it work on any machine

### ISSUE THREAD

**Issue by f4grx** [amitesh-singh/FASTUSBasp#6]
Hello,
wanted to build it, but:

```
me@machine~/code/fastusbasp $ cat config.cmake
# Always declare this before stm32-toolchain.cmake
#
set(MCU STM32F1)
set(LIBOPENCM3_DIR "/home/ami/repos/libopencm3")
set(SERIAL_PORT "/dev/ttyUSB0")
```
No chance this will work here :)

Can you include libopencm3 in your source tree, or manage it as a configurable dependency via, eg, a cmake variable?

thanks

**Comment by f4grx** [comment]
OK, config.cmake works for this

however now I get this:
```
[ 75%] Linking CXX executable fastusbasp.elf
cd /home/user/code/fastusbasp/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/fastusbasp.dir/link.txt --verbose=1
/home/user/toolchains/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-g++    -fdata-sections -ffunction-sections -fno-exceptions -Wall --std=gnu++14 -Os -ggdb -mcpu=cortex-m3 -mthumb -mthumb-interwork -msoft-float -Wextra -Wshadow -Wredundant-decls    -flto -T /home/user/code/fastusbasp/libopencm3.ld -nostartfiles -lopencm3_stm32f1 -lc -specs=nosys.specs -Wl,--gc-sections -Wl,--relax CMakeFiles/fastusbasp.dir/main.cpp.obj  -o fastusbasp.elf  -L/home/user/code/libopencm3/lib  -L/home/user/code/libopencm3/lib/stm32/f1 -lopencm3_stm32f1 -L/home/user/code/fastusbasp/src/../lib/ ../lib/libstm32f1cpp.a -lopencm3_stm32f1
/home/user/toolchains/gcc-arm-none-eabi-7-2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m/libc.a(lib_a-fini.o): In function `__libc_fini_array':
fini.c:(.text.__libc_fini_array+0x26): undefined reference to `_fini'
collect2: error: ld returned 1 exit status
src/CMakeFiles/fastusbasp.dir/build.make:95: recipe for target 'src/fastusbasp.elf' failed
```

It seems related to this:
https://bugs.launchpad.net/gcc-arm-embedded/+bug/1680293

Probably a problem in the linker script?

**Comment by f4grx** [comment]
looks like this
http://www.chibios.com/forum/viewtopic.php?t=4172

Here is a patch that make it build with latest libopencm3 from git:

```
diff --git a/src/main.cpp b/src/main.cpp
index 7646406..d9b8644 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -651,3 +651,9 @@ config_setup(usbd_device *usb, uint16_t wValue)
                                   USB_REQ_TYPE_TYPE,
                                   isp_control_endpoint);
 }
+
+extern "C" {
+void _fini(void);
+}
+
+__attribute__((used)) void _fini(void) {}
```

**Comment by amitesh-singh** [comment]
> Hello,
> wanted to build it, but:
> 
> ```
> me@machine~/code/fastusbasp $ cat config.cmake
> # Always declare this before stm32-toolchain.cmake
> #
> set(MCU STM32F1)
> set(LIBOPENCM3_DIR "/home/ami/repos/libopencm3")
> set(SERIAL_PORT "/dev/ttyUSB0")
> ```
> 
> No chance this will work here :)
> 
> Can you include libopencm3 in your source tree, or manage it as a configurable dependency via, eg, a cmake variable?
> 
> thanks

I'd already provided a guide which clearly mentions what needs to be done to compile.

**Comment by amitesh-singh** [comment]
> looks like this
> http://www.chibios.com/forum/viewtopic.php?t=4172
> 
> Here is a patch that make it build with latest libopencm3 from git:
> 
> ```
> diff --git a/src/main.cpp b/src/main.cpp
> index 7646406..d9b8644 100644
> --- a/src/main.cpp
> +++ b/src/main.cpp
> @@ -651,3 +651,9 @@ config_setup(usbd_device *usb, uint16_t wValue)
>                                    USB_REQ_TYPE_TYPE,
>                                    isp_control_endpoint);
>  }
> +
> +extern "C" {
> +void _fini(void); //prevent C++ function name mangling
> +}
> +
> +__attribute__((used)) void _fini(void) {} //make the linker happy
> ```
> 
> edit: the compiled binary works with avrdude.

I think you are using a gcc version which has this bug. 
mine is 
_# arm-none-eabi-gcc --version
arm-none-eabi-gcc (Arch Repository) 8.3.0_

**Comment by amitesh-singh** [comment]
woah!, I am also getting similar compilation errors now.
Thanks for the patch. I will add it
