### ISSUE TITLE
Seeing this error upon compilation on WLS (Windows Linux Subsystem)

### ISSUE THREAD

**Issue by RandoSY** [amitesh-singh/FASTUSBasp#7]
Howdy,

Thanks for this cool project. Lot's of interesting embedded C++ going on!

I have this error just now ...

[ 75%] Linking CXX executable fastusbasp.elf
/usr/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m/libc.a(lib_a-fini.o): In function `__libc_fini_array':
fini.c:(.text.__libc_fini_array+0x26): undefined reference to `_fini'
collect2: error: ld returned 1 exit status
src/CMakeFiles/fastusbasp.dir/build.make:95: recipe for target 'src/fastusbasp.elf' failed
make[2]: *** [src/fastusbasp.elf] Error 1
CMakeFiles/Makefile2:157: recipe for target 'src/CMakeFiles/fastusbasp.dir/all' failed
make[1]: *** [src/CMakeFiles/fastusbasp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I think I'm compiling OK, but there is an error in the final (no pun intended) link step.

Compilation under Ubuntu 19.04, as a Oracle Virtual Box VM works fine. 

Best,

R.

**Comment by amitesh-singh** [comment]
Hello,

Which version of gcc are you using? 
Have you checked at this: https://bugs.launchpad.net/gcc-arm-embedded/+bug/1680293
it might help.
